on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - msvc_config: x64-Release
            msvc_arch: amd64
            build_type: RelWithDebInfo
          - msvc_config: x86-Release
            msvc_arch: amd64_x86
            build_type: RelWithDebInfo
          - msvc_config: x64-Debug
            msvc_arch: amd64
            build_type: Debug
          - msvc_config: x86-Debug
            msvc_arch: amd64_x86
            build_type: Debug
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}
      - run: cmake -B out/build/${{ matrix.msvc_config }} -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_INSTALL_PREFIX:PATH=${{ github.workspace }}/out/install/${{ matrix.msvc_config }}
      - run: cmake --build out/build/${{ matrix.msvc_config }}
      - run: cmake --install out/build/${{ matrix.msvc_config }}
      - uses: actions/upload-artifact@v2
        with:
          name: RudeWindowFixer-${{ matrix.msvc_config }}
          path: out/install/${{ matrix.msvc_config }}/
